name: knowledger

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  meili:
    image: getmeili/meilisearch:v1.6
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterkey
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
